name: Backend CI - Build & Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend_ci.yml'

jobs:
  build_and_push_backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Azure login
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Login to Azure Container Registry (ACR)
    - name: Login to ACR
      run: az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}

    # Build and Push Backend Docker Image
    - name: Build and Push Backend Image
      run: |
        docker build -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/backend:latest ./backend
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/backend:latest

    # Logout
    - name: Logout from Azure
      run: az logout
      if: always()
