name: Backend CI

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend_ci.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend_ci.yml"

jobs:
  build_and_push_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Azure using service principal JSON
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Log in to ACR using secrets
      - name: Docker Login
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} \
          --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      # Build and push backend image
      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:latest ./backend
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:latest
