name: CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy (demo)
        run: |
          echo "============================="
          echo "🚀 Deploying to Azure... (demo)"
          echo "============================="
          sleep 5
          echo "✅ Deployment simulation complete"
