name: CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/cd.yml"
      - "deploy/**"
      - "frontend/**"
      - "backend/**"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy (demo)
        run: echo "Deploying to Azure... (demo)"
      # Replace with real az/kubectl commands if you choose to do a live deploy
