name: CI Pipeline

on:
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps (if package.json present)
        run: |
          if [ -f package.json ]; then
            npm ci || npm install
          else
            echo "No package.json found, skipping install."
          fi

      - name: Run tests (if defined)
        run: |
          if [ -f package.json ] && npm run | grep -q " test"; then
            npm test
          else
            echo "No tests defined, passing."
          fi

